users/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import signup,login_page,logout_page

app_name="users"

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
]

video_dars_app/urls.py
from django.urls import path
from .views import home,mavzular

app_name='video_dars_app'

urlpatterns = [
    path('',home,name='home'),
    path('lesson/<str:title>/',mavzular,name='mavzular'),
]

video_darslar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("video_dars_app.urls")),
    path('users/',include("users.urls")),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Users(AbstractUser):
    image=models.ImageField(upload_to='users/images/')

    def __str__(self):
        return self.username
    


class UserProfile(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=100)
    # Boshqa kerakli ma'lumotlar

video_dars_app/models.py
from django.db import models

class Card(models.Model):
    image=models.ImageField(upload_to='card/image/')
    title=models.CharField(max_length=150,unique=True)
    subtitle=models.CharField(max_length=200)

    def __str__(self):
        return self.title
    
class Mavzu(models.Model):
    title=models.CharField(max_length=150)
    card=models.ForeignKey(Card,on_delete=models.CASCADE,related_name='mavzular')

    def __str__(self):
        return self.title
    
class Video(models.Model):
    image=models.ImageField(upload_to='video/images/')
    video=models.FileField(upload_to='video/videos/')
    title=models.CharField(max_length=150)
    mavzu=models.ForeignKey(Mavzu,on_delete=models.CASCADE,related_name='videolar')

    def __str__(self):
        return self.title
    
class Test(models.Model):
    title=models.CharField(max_length=150)
    batafsil=models.TextField()

    def __str__(self):
        return self.title

users/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .form import SignUpForm,LogInForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required



def login_required_decorator(func):
    return login_required(func, login_url="login")

@login_required_decorator
def logout_page(request):
    logout(request)
    return redirect(reverse('video_dars_app:home'))

def signup(request):
    sign=SignUpForm()
    if request.method == 'POST':
        sign=SignUpForm(request.POST, request.FILES)
        if sign.is_valid():
            sign.save()
            return redirect(reverse('video_dars_app:home'))
    return render(request, "auth/signup.html", {'sign':sign})

def login_page(request):
    errors=""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password) 
        if user is not None:
            login(request, user)
            return redirect(reverse('video_dars_app:home'))
        else:
            errors+="Login yoki parol noto'g'ri. Iltimos qaytadan kiriting!"
            return render(request, "auth/login1.html",{"errors":errors})

    return render(request, "auth/login1.html",{"errors":errors})


@login_required_decorator
def home_page(request):
    return render(request, 'home.html')

video_dars_app/views.py
from django.shortcuts import render
from .models import Card,Test

# Create your views here.
def home(request):
    cards=Card.objects.all()
    # test=Test.objects.create(title="test",batafsil="test batafsil")
    # test.save()
    return render(request, 'index.html', {'cards':cards})

def mavzular(request,title):
    card=Card.objects.get(title=title)
    return render(request, 'mavzular.html', {'card':card})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
</head>

<body style="background-image: linear-gradient(to right, #fbc2eb, #a6c1ee);">
    {% include 'detail/navbar.html' %}

    {% block content %}

    {% endblock %}

    {% include 'detail/footer.html' %}
</body>

</html>

templates/detail/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
</footer>

templates/detail/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg border-bottom border-success fs-4"
    style="background-image: linear-gradient(to left, #fbc2eb, #a6c1ee);">
    <div class="container-fluid">
        <a href="{% url 'video_dars_app:home' %}">
            <img src="{% static 'image/fire_tiger.jpg' %}"
                style="width: 40px;height: 40px; border-radius: 10px;margin-right: 10px;" alt="">
        </a>
        <a class="navbar-brand fst-italic" href="{% url 'video_dars_app:home' %}">White Hacker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'video_dars_app:home' %}">Home</a>
                </li>

            </ul>

            {% if request.user.is_authenticated %}
            <a href="" class="nav-link text m-2">{{ request.user.first_name }}</a>
            <a class="btn btn-primary m-2" type="button" href="{% url 'users:logout' %}">Logout</a>
            {% endif %}

            {% if not request.user.is_authenticated %}
            <a class="btn btn-outline-success border border-2 m-2" href="{% url 'users:login' %}"
                style="background: rgb(248, 221, 13);" type="submit">Kirish</a>
            <a class="btn btn-outline-success border border-2" href="{% url 'users:signup' %}"
                style="background: green;color: white;" type="submit">Ro'yhatdan o'tish</a>
            {% else %}

            {% endif %}
        </div>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluit mt-5 mb-5">
    <h1 class="mt-5 text-center mb-5 border border-success border-3 p-0 rounded-4">👇 📚📖📜✍ ▶ Kurslar ▶ ✍📜📖📚 👇
    </h1>
    <div class="row mt-5 mb-5">
        {% for c in cards %}
        <div class="col-3 mb-4  d-flex justify-content-center">
            <a href="{% url 'video_dars_app:mavzular' c.title %}" class="nav-link">
                <div class="card border border-2 border-success rounded-5" style="width: 20rem;">
                    <img src="{{ c.image.url }}" style="width: 100%;height: 300px;" class="card-img-top rounded-5"
                        alt="...">
                    <div class="card-body text-center border rounded-5"
                        style="background: linear-gradient(to right, #fbc2eb, #a6c1ee); border-top: 5px;">
                        <h5 class="card-title ">{{ c.title }}</h5>
                        <div class="overflow-auto mb-3" style="height: 80px;">
                            <p class="card-text">{{ c.subtitle }}</p>
                        </div>
                        {% if user.is_authenticated %}
                        <a href="{% url 'video_dars_app:mavzular' c.title %}" class="btn btn-success rounded-5 fs-4"
                            style="width: 100%;">Ko'rish</a>
                        {% else %}
                        <a href="{% url 'users:signup' %}" class="btn btn-success rounded-5 fs-4" style="width: 100%;">Ko'rish</a>
                        {% endif %}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

templates/mavzular.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}

<h1 class="text-center m-5 title">{{ card }}</h1>


<div class="container-fluid">
    <div class="row">
        <div class="col-3 border border-success border-3 p-0 rounded-4 border-bottom rounded-4 overflow-auto"
            style="height: 90vh;position: relative;overflow: hidden;">
            <!-- <------------------------------------ -->
            <div class="accordion p-2" id="accordionExample">
                {% for m in card.mavzular.all %}
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#{{ m.id }}" aria-expanded="false" aria-controls="{{ m.id }}">
                            {{ m.title }}
                        </button>
                    </h2>
                    <div id="{{ m.id }}" class="accordion-collapse collapse " data-bs-parent="#{{ m.id }}">
                        <div class="accordion-body">
                            {% for v in m.videolar.all %}
                            <button class="btn btn-outline-primary"
                                onclick=" changeVideo('{{ v.title }}','{{ v.video.url }}', '{{ v.image.url }}' ) "
                                style="width: 100%;margin-top: 10px;">
                                {{ v.title }}
                            </button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- ------------------------------------+ -->
        </div>
        <div class="col-9 text-center">
            <div style="height: 90vh;">
                <video id="video_url" poster="" src="" loop style="width: 100%;height: 92%;"
                    class="border-bottom border-success rounded-4 border border-4 p-0" controls></video>
                <div class="border border-success border-2 p-0 rounded-4 border-bottom rounded-4"
                    style="background: linear-gradient(to left, #fbc2eb, #a6c1ee);">
                    <h3 id="video_title">Video title</h3>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    function changeVideo(t, v, r) {
        var video = document.getElementById("video_url");
        var title = document.getElementById("video_title");

        video.src = v;
        video.poster = r;
        title.innerHTML = t;
    }
</script>

{% endif %}



{% endblock %}

templates/payme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payme bo'limi</title>
</head>
<body>
    
</body>
</html>